name: List EC2 Instances

on:
  push:
    branches:
      - main
      
  workflow_dispatch:  

permissions:
  id-token: write
  contents: read

jobs:
  list-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Debug OIDC Token
      run: |
        TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" | jq -r '.value')
        echo "$TOKEN" | cut -d. -f2 | base64 -d 2>/dev/null | jq .

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
        aws-region: ap-southeast-2

    - name: List EC2 Instances
      run: |
        aws ec2 describe-instances \
          --query "Reservations[*].Instances[*].InstanceId" \
          --output table
